name: ServerCore
version: 2.6.4
api-version: 1.12
main: kr.sul.servercore.ServerCore
author: SuL
softdepend:
  - CrackShotAddition
  - NBTAPI
  - ProtocolLib
description: "Core Plugin"

commands:
  서버저장:
    description: save server