name: ServerCore
version: 1.19.4
api-version: 1.19
main: kr.sul.servercore.ServerCore
author: SuL
load: STARTUP
description: "Core Plugin"
depend: [KotlinLoader]

commands:
  서버저장:
    description: save server
